if ( GetLocale() ~= "deDE" ) then return end

local addon, ns = ...
ns.L = {
	["Enabled"] = "Enabled",
	["Global Font"] = "Global Font",
	["Outline"] = "Outline",
	["Force Shown"] = "Force Shown",
	["Tooltip On"] = "Tooltip On",
	["Font Size"] = "Font Size",
	["Font"] = "Font",
	["Justify"] = "Justify",
	["Parent"] = "Parent",
	["Anchor"] = "Anchor",
	["X Offset"] = "X Offset",
	["Y Offset"] = "Y Offset",
	["Frame Strata"] = "Frame Strata",
	["Show Note"] = "Show Note",
	["ClickDesc"] = "Click to send tell.",
	["AltClickDesc"] = "Alt+Click to invite.",
	["Show Icon"] = "Show Icon",
	["Friend List"] = "Friend List",
	["Friends"] = "Friends",
	["Friends Online"] = "Friends Online",
	["BNet Friends"] = "BNet Friends",
	["Note"] = "Note",
	["(AFK)"] = "(AFK)",
	["(DND)"] = "(DND)",
}