if ( GetLocale() ~= "frFR" ) then return end

local addon, ns = ...
ns.L = {
	["Enabled"] = "Activé",
	["Global Font"] = "Font mondiale",
	["Outline"] = "Aperçu",
	["Force Shown"] = "Voir dans bataille",
	["Tooltip On"] = "Sur Tooltip",
	["Font Size"] = "Taille de la police",
	["Font"] = "Type de police",
	["Justify"] = "Alignement du texte",
	["Parent"] = "Cadre parent",
	["Anchor"] = "D'ancrage",
	["X Offset"] = "X Alignement",
	["Y Offset"] = "Y Alignement",
	["Frame Strata"] = "Cadre strates",
	["Show Note"] = "Voir la note",
	["ClickDesc"] = "Cliquez ici pour envoyer dire.",
	["AltClickDesc"] = "Alt+Clic d'inviter.",
	["Show Icon"] = "Afficher l'icône",
	["Friend List"] = "Amis List",
	["Friends"] = "Amis",
	["Friends Online"] = "Amis Online",
	["BNet Friends"] = "BNet Amis",
	["Note"] = "Note",
	["(AFK)"] = "(AFK)",
	["(DND)"] = "(DND)",
}