if ( GetLocale() ~= "zhTW" ) then return end

local addon, ns = ...
ns.L = {
	["Enabled"] = "啟用",
	["Global Font"] = "全域字型",
	["Outline"] = "外框線",
	["Force Shown"] = "總是顯示",
	["Tooltip On"] = "開啟提示資訊",
	["Font Size"] = "字型大小",
	["Font"] = "字型",
	["Justify"] = "對齊",
	["Parent"] = "依附",
	["Anchor"] = "錨點",
	["X Offset"] = "水平位移",
	["Y Offset"] = "垂直位移",
	["Frame Strata"] = "框架層級",
	["Show Note"] = "顯示註記",
	["ClickDesc"] = "點擊傳送悄悄話",
	["AltClickDesc"] = "Alt+點擊傳送組隊邀請",
	["Show Icon"] = "顯示小圖示",
	["Friend List"] = "好友名單",
	["Friends"] = "好友",
	["Friends Online"] = "線上好友",
	["BNet Friends"] = "戰網好友",
	["Note"] = "註記",
	["(AFK)"] = "(AFK)",
	["(DND)"] = "(DND)",
}